const THEMES = [
    { id: 'work', emoji: '🏢', title: '회사/학교', desc: '상사와 조별과제 잔혹사' },
    { id: 'transit', emoji: '🚇', title: '대중교통', desc: '출퇴근길 지옥철의 빌런들' },
    { id: 'digital', emoji: '💻', title: '디지털/IT', desc: '기계가 나를 억까할 때' },
    { id: 'relationship', emoji: '🤬', title: '인간관계', desc: '눈치 밥 말아먹은 지인들' },
    { id: 'daily', emoji: '🤦', title: '머피의 법칙', desc: '꼭 바쁠 때만 터지는 일상' }
];

const QUESTION_BANK = {
    'work': [
        { emoji: '👨‍💼', title: '퇴근 요정', desc: '금요일 오후 5시 50분, "김대리, 이거 급한건데 월요일 아침까지 될까?"', actionLeft: '조용히 야근하기', actionRight: '"월요일에 하겠습니다" 선언' },
        { emoji: '📧', title: '주말 연락', desc: '일요일 오후 2시 카톡: "주말에 미안한데 지난번 엑셀 파일 어딨지?"', actionLeft: '친절하게 찾아주기', actionRight: '월요일 아침까지 읽씹하기' },
        { emoji: '📑', title: '조별 무임승차', desc: '조별과제 단톡방: "제가 피피티랑 발표는 맹장염이라 못해서... 자료조사 할게요!"', actionLeft: '어쩔 수 없지.. 알겠습니다', actionRight: '"그럼 이름 뺍니다" 통보' },
        { emoji: '😤', title: '답정너 회의', desc: '"다들 자유롭게 의견 내봐." (내면 다 묵살하고 결국 본인 뜻대로 함)', actionLeft: '영혼 없는 리액션하기', actionRight: '"어차피 정하셨잖아요" 팩폭' },
        { emoji: '🗑️', title: '기적의 논리', desc: '"내가 언제 그렇게 하라고 했어?" (분명히 어제 그렇게 하라고 지시했음)', actionLeft: '제가 착각했나 봅니다..', actionRight: '어제 녹음본 틀어버리기' },
        { emoji: '📝', title: '무한 수정', desc: '"다 좋은데, 느낌이 조금 안 사네. 처음 시안 느낌으로 폰트만 조금 바꿔봐." (수정 14번째)', actionLeft: '알겠습니다! 다시 할게요', actionRight: '"처음 시안이 낫네요" 던지기' },
        { emoji: '⏰', title: '시간 도둑', desc: '회의시간에 본인 라떼 시절 군대 이야기로 40분 날려먹음.', actionLeft: '고개 끄덕이며 딴생각하기', actionRight: '"그래서 결론이 뭐죠?" 끊기' },
        { emoji: '☕', title: '강제 티타임', desc: '바빠 죽겠는데 상사가 커피 한잔 하자고 불러내서 1시간 동안 자기 하소연함.', actionLeft: '호응해주며 들어주기', actionRight: '"저 바빠서 이만" 일어서기' },
        { emoji: '💳', title: '법카 빌런', desc: '회식비 n빵인데 본인만 제일 비싼 메뉴 시키고 법카 안 긁히니까 엔빵하자고 함.', actionLeft: '더러워서 그냥 돈 내기', actionRight: '"대리님은 따로 결제하시죠"' },
        { emoji: '💻', title: '저장 안 함', desc: '3시간 동안 쓴 보고서, 날아갔는데 상사가 "왜 아직도 안 주냐"고 재촉함.', actionLeft: '울면서 밤새 다시 쓰기', actionRight: '"날아갔습니다" 당당히 말하기' },
        { emoji: '😷', title: '출근 강요', desc: '코로나/독감인데 "나때는 링거 맞고 출근했어" 시전.', actionLeft: '마스크 끼고 출근하기', actionRight: '"노동청 신고할까요?" 묻기' },
        { emoji: '🗣️', title: '뒷담화 스피커', desc: '비밀로 해달라고 한 이야기 다음 날 부서 전체가 다 알고 있음.', actionLeft: '앞으로 말 안 섞기', actionRight: '모두 앞에서 공개 저격하기' },
        { emoji: '🍔', title: '막내의 숙명', desc: '점심 메뉴 고르라면서 "나는 아무거나. 아, 근데 짜장면은 어제 먹었고 국물은 튀니까 빼고." 제한조건 10개.', actionLeft: '머리 싸매고 메뉴 찾기', actionRight: '"그럼 부장님이 고르시죠"' },
        { emoji: '🎁', title: '명절 선물', desc: '임원들은 한우 세트 받고, 말단 직원들은 유통기한 임박 샴푸 세트 받음.', actionLeft: '당근마켓에 나눔하기', actionRight: '임원실 문 앞에 두고 오기' },
        { emoji: '🤷', title: '떠넘기기', desc: '다른 부서 일인데 "김대리가 엑셀 잘하니까 이거 하나만 해줘" 하고 떠넘김.', actionLeft: '한숨 쉬며 야근으로 처리', actionRight: '"제 업무 아닙니다" 칼거절' },
        { emoji: '🖨️', title: '프린터 고장', desc: '내가 급하게 인쇄하려고 하면 꼭 종이 걸리거나 토너 다 떨어짐.', actionLeft: '직접 수리/교체하기', actionRight: '에라 모르겠다 방치하기' },
        { emoji: '📞', title: '퇴근 후 전화', desc: '퇴근하고 샤워하고 나왔는데 부재중 전화 5통 (사수).', actionLeft: '급히 전화 다시 걸기', actionRight: '내일 아침까지 비행기 모드' },
        { emoji: '📅', title: '갑작스러운 연차 반려', desc: '3주 전부터 결재 올린 연차, 전날 오후 5시에 "내일 바쁜데 꼭 쉬어야 하나?"', actionLeft: '네.. 출근하겠습니다', actionRight: '"티켓 예약 끝났습니다" 강행' },
        { emoji: '🧊', title: '에어컨 전쟁', desc: '나는 더워 죽겠는데 상사가 춥다고 에어컨 끄고 창문 엶.', actionLeft: '땀 뻘뻘 흘리며 참기', actionRight: '개인용 선풍기 강풍 켜기' },
        { emoji: '👀', title: '감시자', desc: '모니터 뒤로 슥 지나가면서 내가 뭐 하는지 10초간 노골적으로 쳐다봄.', actionLeft: '아무렇지 않은 척 일하기', actionRight: '모니터 바탕화면 띄워버리기' },
        { emoji: '📝', title: '회의록 셔틀', desc: '본인들은 떠들기만 하고, 회의록 정리해서 올리면 "이 말은 이런 뉘앙스가 아니었는데?" 태클 걺.', actionLeft: '죄송합니다 하고 재수정', actionRight: '"그럼 직접 쓰시죠" 던지기' },
        { emoji: '🏆', title: '가로채기', desc: '내가 밤새 기획한 아이디어, 부장이 임원 회의에서 본인 아이디어인 양 발표함.', actionLeft: '속으로 분삭이기', actionRight: '"제 기획안을 잘~ 설명해주셨네요!"' },
        { emoji: '😡', title: '분노 조절 실패', desc: '자기 기분 안 좋은 날은 팀원들한테 하루종일 시비 털고 화냄.', actionLeft: '최대한 눈에 안 띄게 숨기', actionRight: '"부장님 기분 푸세요~" 비꼬기' },
        { emoji: '😴', title: '조별 잠수', desc: '발표 전날 밤 11시, 파트장(잠수): "저 지금 알바 끝났어요 ㅠㅠ 어디까지 했나요?"', actionLeft: '내가 남은 거 다 하기', actionRight: '"이미 이름 빼서 제출했습니다"' },
        { emoji: '🎓', title: '교수님의 기적', desc: '"이번 시험은 교재 안에서만 나옵니다." (교재에 없는 논문 내용 출제)', actionLeft: '내 머리를 원망하기', actionRight: '강의평가에 테러하기' }
    ],
    'transit': [
        { emoji: '🎒', title: '백팩 어택', desc: '지하철 만원인데 등산 배낭 메고 몸 비틀어서 명치 가격함.', actionLeft: '조용히 몸을 피하기', actionRight: '"가방 좀 내리시죠!" 외치기' },
        { emoji: '🏃', title: '간발의 차', desc: '눈앞에서 지하철 문 닫히고, 다음 열차는 15분 뒤에 옴.', actionLeft: '이어폰 꽂고 멍 때리기', actionRight: '스크린도어 쾅 치기' },
        { emoji: '📱', title: '스피커폰 빌런', desc: '버스 맨 뒷자리에서 이어폰 안 끼고 트로트/유튜브 최대 볼륨으로 시청함.', actionLeft: '내 노이즈캔슬링 켜기', actionRight: '나도 스피커폰으로 헤비메탈 틈' },
        { emoji: '💺', title: '자리 스틸', desc: '빈자리 나서 앉으려는데, 저 멀리서 아줌마가 가방 먼저 냅다 던짐.', actionLeft: '머쓱하게 다른 칸 가기', actionRight: '가방 치우고 냅다 앉아버리기' },
        { emoji: '🦵', title: '쩍벌남/다리꼬기', desc: '내 무릎에 본인 신발 밑창 닿을 정도로 다리 꼬고 앉아서 핸드폰 함.', actionLeft: '몸을 구겨서 피하기', actionRight: '내 발로 슬쩍 밀어버리기' },
        { emoji: '🌧️', title: '우산 테러', desc: '비 오는 날, 젖은 우산 안 접고 내 다리에 빗물 뚝뚝 떨어뜨림.', actionLeft: '바짓가단 털며 뒤로 물러서기', actionRight: '"물 튀잖아요!" 소리치기' },
        { emoji: '🚷', title: '입구 컷', desc: '안에 자리 텅텅 비었는데 문 앞에 서서 절대 안으로 안 들어가는 사람.', actionLeft: '그냥 입구에 같이 끼어있기', actionRight: '"좀 들어갑시다!" 밀치고 가기' },
        { emoji: '🚪', title: '내릴게요', desc: '버스 멈추지도 않았는데 뒤에서 밀치면서 "내려요!!" 소리침.', actionLeft: '황급히 길 비켜주기', actionRight: '"멈추면 움직이세요!" 쏘아붙임' },
        { emoji: '🤢', title: '냄새 테러', desc: '옆자리에 앉은 사람한테서 어제 먹은 마늘 삼겹살+소주+담배 냄새 풀풀 남.', actionLeft: '숨 참고 입으로만 숨쉬기', actionRight: '보란 듯이 코 틀어막고 일어나기' },
        { emoji: '💤', title: '수면 유도제', desc: '옆자리 사람이 졸면서 내 어깨에 머리를 3번 연속으로 기댐.', actionLeft: '조용히 어깨 내어주기', actionRight: '갑자기 확 피해서 넘어뜨리기' },
        { emoji: '🤧', title: '노마스크 기침', desc: '내 얼굴 바로 옆에서 입도 안 가리고 기침/재채기 뿜어냄.', actionLeft: '얼굴 찡그리며 외면하기', actionRight: '"입 좀 가리고 하세요!" 정색하기' },
        { emoji: '🛑', title: '무정차 통과', desc: '손 흔들었는데 버스 기사님이 나와 눈 마주치고도 쿨하게 지나감.', actionLeft: '허탈하게 다음 버스 기다리기', actionRight: '버스 번호 적고 민원 넣기' },
        { emoji: '🚶‍♂️', title: '환승 지연', desc: '내 앞에 걷는 세 명이 환승 통로 길막하고 좀비처럼 느리게 걸어감.', actionLeft: '뒤에서 천천히 따라가기', actionRight: '"지나갈게요!" 외치며 돌파하기' },
        { emoji: '💳', title: '잔액 부족', desc: '뒤에 줄 쫙 서있는데, 카드 찍었더니 "잔액이 부족합니다." 3번 연속 뜸.', actionLeft: '죄송합니다 하고 당황하며 내림', actionRight: '기사님한테 현금 내고 뻐기기' },
        { emoji: '❄️', title: '북극 열차', desc: '여름에 에어컨 바로 밑자리인데 조절바 부서져서 얼어 죽을 것 같음.', actionLeft: '팔짱 끼고 부들부들 떨기', actionRight: '당장 일어나서 다른 칸 이동' },
        { emoji: '🧄', title: '취식 빌런', desc: '지하철에서 냄새 심한 햄버거나 김밥 쩝쩝거리며 먹음.', actionLeft: '못 본 척 이어폰 꽂기', actionRight: '"여기가 식당입니까?" 일침' },
        { emoji: '🎶', title: '이어폰 누음', desc: '이어폰 꼈는데 무슨 노래 듣는지 둥둥거리는 비트가 내 귓막까지 때림.', actionLeft: '내 노래 소리를 더 키우기', actionRight: '"볼륨 좀 줄여주세요" 톡톡' },
        { emoji: '🚏', title: '잘못 탄 버스', desc: '한참 가다 폰에서 고개 들었는데 반대 방향으로 가는 버스임.', actionLeft: '다음 정거장에서 조용히 내림', actionRight: '나 자신에게 욕 시원하게 함' },
        { emoji: '👫', title: '커플의 애정행각', desc: '출근길 만원 지하철, 내 바로 앞에서 커플이 껴안고 쪽쪽거림.', actionLeft: '허공 응시하며 모른 척', actionRight: '사이에 끼어들어서 방해하기' },
        { emoji: '🛒', title: '캐리어 어택', desc: '여행객이 끄는 캐리어 바퀴에 발목 세게 채임. (사과 안 함)', actionLeft: '발목 부여잡고 끙끙대기', actionRight: '"발을 쳤으면 사과를 해야죠!"' },
        { emoji: '☂️', title: '장마철 찝찝함', desc: '비 쏟아지는데 내 앞사람 우산 끝이 정확히 내 바지를 다 적심.', actionLeft: '한숨 쉬고 내 우산으로 막기', actionRight: '앞사람 어깨 쳐서 똑바로 들라 함' },
        { emoji: '🚦', title: '신호등 타이밍', desc: '내가 건너려 하면 무조건 빨간불로 바뀜. (오늘만 4번째)', actionLeft: '포기하고 폰 보기', actionRight: '무단횡단 충동 참으며 욕하기' },
        { emoji: '💸', title: '택시 승차거부', desc: '비 오는 날 택시 잡았는데, 창문만 내리고 "어디 가?" 하더니 쌩 가버림.', actionLeft: '비 맞으며 다음 택시 잡기', actionRight: '차 번호판 외워서 120 신고하기' },
        { emoji: '🛴', title: '킥보드 고라니', desc: '인도로 걷고 있는데 뒤에서 소리도 없이 전동 킥보드가 스치고 지나감.', actionLeft: '놀라서 가슴 쓸어내리기', actionRight: '지나가는 뒷통수에 쌍욕 발사' },
        { emoji: '🚧', title: '도로 공사', desc: '바빠 죽겠는데 내가 탄 버스 차선만 공사 중이라 20분째 멈춰있음.', actionLeft: '기사님만 원망하며 대기', actionRight: '당장 문 열어달라고 해서 뜀' }
    ],
    'digital': [
        { emoji: '❌', title: 'X버튼 낚시', desc: '무료 게임 광고 끝났는데, 닫기(X) 버튼이 가짜라서 앱스토어로 이동됨.', actionLeft: '조용히 원래 앱으로 돌아가기', actionRight: '그 게임 평점에 별 1개 테러하기' },
        { emoji: '🔋', title: '배터리 1%', desc: '중요한 연락 기다리는데 배터리 1% 남았고 보조배터리 안 챙김.', actionLeft: '초절전 모드 켜고 화면 끄기', actionRight: '편의점 달려가서 보배 사기' },
        { emoji: '📶', title: '와이파이 고문', desc: '와이파이 안테나는 빵빵한데 정작 인터넷은 한 글자도 안 뜸.', actionLeft: '참을성 있게 3분 기다리기', actionRight: '와이파이 확 끄고 5G 쓰기' },
        { emoji: '💾', title: '업데이트 강제종료', desc: '급하게 피씨 켜서 파일 보내야 하는데 "Windows 업데이트 중 (1/100)" 뜸.', actionLeft: '폰 보면서 기약없이 기다림', actionRight: '강제종료 전원버튼 꾹 누르기' },
        { emoji: '👀', title: '카톡 읽씹', desc: '분명 "1"은 사라졌는데, 하루 종일 답장이 없음 (인스타 스토리는 올라옴).', actionLeft: '바쁜가보다 하고 넘기기', actionRight: '"뭐하냐?" 연속으로 보내기' },
        { emoji: '🎧', title: '블루투스 배신', desc: '조용한 독서실에서 유튜브 틀었는데 블투 이어폰 연결 안 돼서 폰 스피커로 빵 터짐.', actionLeft: '빛의 속도로 소리 끄기', actionRight: '머쓱하게 웃고 짐 싸서 나가기' },
        { emoji: '🔑', title: '비밀번호 지옥', desc: '"영문, 숫자, 특수기호 포함 8자 이상." -> 다 맞춰서 썼더니 "이전에 사용한 비밀번호입니다." 뜸.', actionLeft: '메모장 켜서 새로운 비번 연구', actionRight: '아예 가입 포기해버리기' },
        { emoji: '🔄', title: '무한 로딩', desc: '넷플릭스 한참 재밌는 부분인데 버퍼링 걸려서 빙글빙글 돔.', actionLeft: '돌아올 때까지 기다리기', actionRight: '공유기 코드를 뽑았다 꽂기' },
        { emoji: '🖱️', title: '더블 클릭 오류', desc: '마우스 수명 다해서 한 번 눌렀는데 자꾸 두 번씩 클릭됨 (창 다 닫힘).', actionLeft: '마우스 꾹 눌러서 조심조심 씀', actionRight: '마우스 샷건 치고 새로 주문함' },
        { emoji: '🤦', title: '자동 완성 대참사', desc: '상사한테 "네 알겠습니다" 치려다 "네 알빠임"으로 자동완성 전송됨.', actionLeft: '빛의 속도로 삭제 버튼 누르기', actionRight: '이참에 진짜 사표 던지기' },
        { emoji: '📱', title: '보호필름 기포', desc: '비싼 돈 주고 액정 필름 붙였는데 정중앙에 먼지 들어가서 기포 생김.', actionLeft: '거슬려도 그냥 쓰기', actionRight: '못 참고 확 떼서 버리기' },
        { emoji: '🗑️', title: '휴지통 비움', desc: '바탕화면 정리하다가 필수 파일까지 휴지통에 넣고 비우기 눌러버림.', actionLeft: '복구 프로그램 돌리며 오열', actionRight: '그냥 포기하고 퇴사 생각하기' },
        { emoji: '💳', title: '인증번호 타임아웃', desc: '본인인증 번호 안 와서 3번 다시 누름 -> 한 번에 4개 날아와서 다 입력 실패함.', actionLeft: '1시간 뒤에 다시 시도하기', actionRight: '휴대폰 집어던지기' },
        { emoji: '📸', title: '용량 부족', desc: '역대급 인생샷 찍는 순간 "저장 공간이 부족합니다" 팝업 뜸.', actionLeft: '어플 지우며 공간 만들기', actionRight: '아무 사진이나 100장 연타 삭제' },
        { emoji: '🎮', title: '세이브 전 사망', desc: '보스 거의 다 잡았는데 엄마가 청소기 돌리다 컴퓨터 콘센트 뽑음.', actionLeft: '허탈하게 웃으며 게임 끄기', actionRight: '엄마한테 소리지르며 극대노' },
        { emoji: '🔊', title: '회의 중 음소거 해제', desc: '줌(Zoom) 회의 중인 줄 모르고 엄마가 "밥 먹어라 이 웬수야!!" 소리침.', actionLeft: '조용히 얼굴 붉히며 마이크 끔', actionRight: '엄마 탓하며 채팅방 폭파시킴' },
        { emoji: '💬', title: '삭제된 메시지', desc: '썸남/썸녀가 밤 11시에 보낸 "삭제된 메시지입니다." (끝까지 뭐였는지 안 알려줌)', actionLeft: '궁금해도 쿨하게 넘어가기', actionRight: '잘 때까지 "뭔데??" 캐묻기' },
        { emoji: '🛑', title: '유튜브 광고 2연타', desc: '15초짜리 스킵 불가 광고 2개 연속으로 나옴.', actionLeft: '멍하니 광고 다 보기', actionRight: '프리미엄 결제창 열기' },
        { emoji: '🔌', title: '충전기 단선', desc: '케이블 목 돌아가서 특정 각도로 꺾어 둬야만 충전됨 (조금만 치면 끊김).', actionLeft: '테이프 칭칭 감아서 쓰기', actionRight: '충전기 선 뚝 끊어서 버리기' },
        { emoji: '⌨️', title: '영타 변환', desc: '키보드 안 보고 장문으로 한글 쳤는데 모니터 보니 "dksudgktpdy..." 쳐져있음.', actionLeft: '한숨 쉬고 지운 뒤 다시 침', actionRight: '번역기에 넣어서 한글로 바꿈' },
        { emoji: '🖱️', title: '광고 오클릭', desc: '기사 읽으려고 스크롤 내리다가 튀어나온 배너 광고 잘못 눌러서 팝업창 5개 뜸.', actionLeft: '일일이 x 눌러서 다 끄기', actionRight: '창 전체를 꺼버리기' },
        { emoji: '🎤', title: '시리 급발진', desc: '아무 말도 안 했는데 회의 중에 갑자기 "잘 못 알아들었어요." 하고 시리가 대답함.', actionLeft: '당황하며 얼른 폰 뒤집기', actionRight: '"시리야 조용히 해" 명령하기' },
        { emoji: '⏰', title: '알람 AM/PM', desc: '아침 7시에 알람 맞췄는데 오후 7시(PM)로 맞춰놔서 지각함.', actionLeft: '변명거리 찾으며 미친듯이 뜀', actionRight: '당당하게 "알람 고장" 시전' },
        { emoji: '🔒', title: '아이폰 페이스아이디', desc: '마스크 끼고 얼굴 안식 안 돼서 비밀번호 치려는데 그제야 인식 실패하고 다시 로딩됨.', actionLeft: '침착하게 다시 비번 누름', actionRight: '폰에 욕 박으며 잠금 강제해제' },
        { emoji: '💸', title: '자동 결제', desc: '무료 체험 끝나고 해지하는 거 까먹어서 오늘 아침에 14,900원 결제 문자 옴.', actionLeft: '아깝지만 이번달만 쓰기', actionRight: '고객센터 전화해서 환불 요구' }
    ],
    'relationship': [
        { emoji: '🤝', title: '돈 안 갚는 친구', desc: '내 돈 5만 원 빌려 가놓고 인스타엔 호캉스 가서 오마카세 먹는 사진 올림.', actionLeft: '조심스레 돈 얘기 꺼내기', actionRight: '스토리에 "돈 갚아라" 태그함' },
        { emoji: '🤷‍♂️', title: '무한 지각러', desc: '약속 시간 1시간 지났는데 "지금 씻고 나옴 ㅋㅋ" 카톡 보냄.', actionLeft: '카페에서 혼자 시간 떼우기', actionRight: '나도 바로 집으로 돌아가버림' },
        { emoji: '🤐', title: '비밀 누설', desc: '"너만 알고 있어"라고 말해줬더니 다음 날 내 지인들 다 알고 있음.', actionLeft: '그 친구한테 실망하고 손절각', actionRight: '그 친구 비밀도 싹 다 뿌려버림' },
        { emoji: '🍽️', title: '계산병', desc: '같이 밥 먹을 땐 지갑 안 가져왔다면서, 지가 쏘는 커피(메가커피 1500원) 살 땐 카드 꺼냄.', actionLeft: '속으로 쪼잔하다 욕하기', actionRight: '"밥값이 더 나왔는데?" 정산함' },
        { emoji: '📸', title: '이기적인 프사', desc: '같이 찍은 사진, 내 얼굴은 눈 감고 빵떡처럼 나왔는데 본인만 잘 나온 사진 프사로 해둠.', actionLeft: '사진 내려달라고 좋게 말하기', actionRight: '나도 그 애 엽사 프사로 지정' },
        { emoji: '🙄', title: '내로남불', desc: '자기가 늦는 건 "차가 막혀서", 내가 5분 늦으면 "넌 기본 예의가 없냐?"', actionLeft: '그냥 사과하고 넘어감', actionRight: '논리적으로 팩트리어트 꽂음' },
        { emoji: '🤬', title: '뒷담화 유도', desc: '내 앞에서 남 욕 실컷 해놓고, 다른 사람 앞에선 그 사람과 단짝인 척함.', actionLeft: '어색하게 맞장구 쳐주기', actionRight: '"아까는 욕하더니?" 꽂아버리기' },
        { emoji: '📱', title: '폰딧불이', desc: '같이 밥 먹는데 폰만 보고 대답은 "어, 어." 영혼 없이 함.', actionLeft: '나도 폰이나 꺼내서 봄', actionRight: '폰 뺏어서 화면 덮어버림' },
        { emoji: '✋', title: '연락 두절', desc: '자기 아쉬울 때만 연락하고, 내가 필요해서 연락하면 다음 날 답장 옴.', actionLeft: '읽씹해도 참아주기', actionRight: '카톡 차단/숨김 해버리기' },
        { emoji: '💔', title: '환승 이별', desc: '어제 헤어졌는데 오늘 프사에 새로운 연인이랑 찍은 인생네컷 올라옴.', actionLeft: '눈물 훔치며 차단하기', actionRight: '저격 글 쓰고 쌍욕 박기' },
        { emoji: '🤦‍♀️', title: '답정너 고민 상담', desc: '2시간 동안 징징거려서 해결책 제시해 줬더니 "넌 공감 능력이 떨어져"라며 화냄.', actionLeft: '영혼 없이 공감만 해주기', actionRight: '"그럼 니 알아서 해" 끊음' },
        { emoji: '🎁', title: '가성비 생일선물', desc: '나는 5만 원짜리 향수 사줬는데, 내 생일엔 기프티콘으로 초코우유 하나 보냄.', actionLeft: '마음이 중요하지.. 참기', actionRight: '기프티콘 결제 거절 눌러버림' },
        { emoji: '🗣️', title: '말 끊기 장인', desc: '내가 말 꺼내기만 하면 "아 그건 됐고, 내 얘기 좀 들어봐" 하고 말 자름.', actionLeft: '입 꾹 닫고 들어주기', actionRight: '"나 아직 말 안 끝났어" 끊음' },
        { emoji: '😒', title: '후려치기', desc: '내가 뭐 새로 샀다고 하면 "그 돈 주고 그걸 왜 사? 내 건 얼만데~" 하면서 깎아내림.', actionLeft: '어색하게 미소 지어주기', actionRight: '"니껀 구리잖아" 카운터 침' },
        { emoji: '🍺', title: '술버릇', desc: '술만 마시면 울면서 3시간 동안 전 남친/여친 얘기 무한 반복함.', actionLeft: '토닥토닥 위로해주기', actionRight: '대리기사 부르고 도망감' },
        { emoji: '🤥', title: '허언증', desc: '입만 열면 자기가 아는 인맥, 부자 친척 얘기인데 인증된 적 한 번도 없음.', actionLeft: '"우와 진짜?" 영혼 리액션', actionRight: '"그래서 차는 언제 사는데?"' },
        { emoji: '🏠', title: '자취방 빈대', desc: '내 자취방 놀러 와서 배달 음식 시켜 먹고 치우지도 않고 잠만 자다 감.', actionLeft: '조용히 내가 다 치우기', actionRight: '쓰레기 들려주고 쫓아냄' },
        { emoji: '📝', title: '핑프 (핑거 프린세스)', desc: '네이버에 3초만 검색하면 나오는 걸 굳이 카톡으로 하나하나 다 물어봄.', actionLeft: '귀찮아도 다 검색해서 알려줌', actionRight: '네이버 검색 링크 보내버림' },
        { emoji: '😡', title: '분노 유발 운전', desc: '조수석에 타놓고 "거기서 끼어들어야지! 넌 운전을 왜 그렇게 하냐" 폭풍 훈수.', actionLeft: '참고 목적지까지 운전함', actionRight: '차 세우고 "니가 운전해!" 시전' },
        { emoji: '📸', title: '도촬 충', desc: '내가 하품하거나 이상한 표정 지을 때 몰래 찍어서 단톡방에 올리고 낄낄댐.', actionLeft: '민망해하며 지워달라 함', actionRight: '나도 그 애 자는 엽사 뿌림' },
        { emoji: '🤷‍♀️', title: '선택 장애', desc: '메뉴 고르라니까 아무거나 다 좋다고 해놓고, 막상 시키면 "이건 좀 별론데..." 함.', actionLeft: '다른 메뉴로 다시 고름', actionRight: '"그럼 먹지마" 하고 내거만 먹음' },
        { emoji: '🤑', title: '빈대붙기', desc: '여행 가서 공금으로 산 간식, 밤에 자기 혼자 다 까먹음.', actionLeft: '치사해서 참는다', actionRight: '"만원 더 내놔" 청구함' },
        { emoji: '📞', title: '취중 진담', desc: '새벽 3시에 술 취해서 전화 와놓고, 다음 날 자기는 전혀 기억 안 난다고 함.', actionLeft: '술이 웬수지.. 넘어감', actionRight: '통화 녹음한거 톡방에 뿌림' },
        { emoji: '👀', title: '읽씹은 기본', desc: '내가 카톡하면 읽씹하면서, 단톡방에선 제일 활발하게 떠들고 있음.', actionLeft: '나도 그 친구 말에 대답 안함', actionRight: '단톡방에서 왜 갠톡 씹냐고 저격' },
        { emoji: '🎭', title: '강약약강', desc: '알바생이나 식당 이모님한테는 반말하고 띠껍게 굴면서 직장 상사한텐 간 쓸개 다 빼줌.', actionLeft: '조용히 밥만 먹기', actionRight: '이모님한테 대신 사과하고 손절' }
    ],
    'daily': [
        { emoji: ' USB', title: 'USB의 법칙', desc: 'USB 꽂았는데 안 들어가서 뒤집음 -> 안 들어감 -> 다시 처음대로 꽂으니 들어감.', actionLeft: '피식 웃으며 꽂기', actionRight: '마우스 부숴버리기' },
        { emoji: '☔', title: '우산 딜레마', desc: '아침에 우산 안 챙기면 폭우 쏟아지고, 무겁게 우산 들고 나가면 하루 종일 쨍쨍함.', actionLeft: '내 징크스를 탓함', actionRight: '편의점 우산 사서 부수기' },
        { emoji: '🧻', title: '휴지 실종', desc: '공중 화장실에서 볼일 시원하게 다 보고 났는데 휴지가 없음.', actionLeft: '옆칸 사람에게 노크해서 빌림', actionRight: '팬티 버리고 노팬티로 나감' },
        { emoji: '💧', title: '세면대 물폭탄', desc: '세면대 수도꼭지 틀었는데 스푼에 물이 정통으로 맞아서 내 옷에 쫙 튀김.', actionLeft: '화장실 휴지로 대충 닦기', actionRight: '거울 보며 쌍욕 발사' },
        { emoji: '🍜', title: '라면 물 조절', desc: '한강 라면 피하려고 물 적게 넣었다가 엄청 짜서 물 부었더니 결국 한강 됨.', actionLeft: '밍밍한 라면 억지로 먹기', actionRight: '싱크대에 부어버리고 치킨 시킴' },
        { emoji: '🦶', title: '새끼발가락', desc: '어두운 방에서 걷다가 문지방에 새끼발가락 정통으로 찧음.', actionLeft: '발가락 잡고 3분간 뒹굴기', actionRight: '문지방 걷어차서 엄지발가락도 다침' },
        { emoji: '👖', title: '흰옷 징크스', desc: '큰맘 먹고 흰 셔츠 입은 날 꼭 짬뽕이나 김치찌개 국물 튐.', actionLeft: '퐁퐁 묻혀서 화장실에서 빰', actionRight: '열받아서 짬뽕 그릇 엎기' },
        { emoji: '🏃‍♂️', title: '간발의 차 (엘베)', desc: '엘리베이터 뛰어갔는데 안에 있는 사람이 열림 대신 닫힘 버튼 눌러서 닫힘.', actionLeft: '한숨 쉬고 다음 거 기다림', actionRight: '계단으로 미친듯이 뛰어서 잡기' },
        { emoji: '📦', title: '택배 수령', desc: '하루 종일 집에 있다가 잠깐 분리수거하러 5분 나간 사이에 택배기사님 다녀감.', actionLeft: '경비실 가서 무겁게 들고 옴', actionRight: '택배기사님 차 쫓아서 뛰어감' },
        { emoji: '🧦', title: '양말 웅덩이', desc: '새 양말 신고 화장실 들어갔다가 바닥에 고인 물 정통으로 밟음.', actionLeft: '울며 겨자먹기로 젖은채로 신음', actionRight: '양말 찢어버리고 맨발로 다님' },
        { emoji: '✂️', title: '테이프 미아', desc: '투명 테이프 끝부분 어딘지 못 찾아서 손톱으로 3분 동안 긁고 있음.', actionLeft: '인내심을 가지고 끝내 찾음', actionRight: '테이프 뭉치 씹어버리기' },
        { emoji: '🔋', title: '충전 징크스', desc: '자기 전에 폰 충전기 꽂아뒀는데, 아침에 일어나 보니 코드 살짝 빠져서 충전 0%.', actionLeft: '출근길에 강제 디지털 디톡스', actionRight: '하루 연차 내고 잠이나 더 잠' },
        { emoji: '🦟', title: '여름밤 모기', desc: '불 끄면 귓가에 윙~ 소리 나서 불 켜면 사라짐. (무한 반복)', actionLeft: '이불 뒤집어쓰고 더위 참기', actionRight: '불 켜고 잡을 때까지 밤샘' },
        { emoji: '🍔', title: '감자튀김 실종', desc: '포장해서 집 와서 열어보니 햄버거 세트에 감자튀김 누락됨.', actionLeft: '햄버거만 먹고 콜라 남김', actionRight: '다시 차 끌고 매장 가서 따짐' },
        { emoji: '🎤', title: '음이탈', desc: '노래방에서 내 차례에 제일 자신 있는 노래 불렀는데 첫 소절부터 삑사리 남.', actionLeft: '머쓱하게 웃고 마이크 넘김', actionRight: '"마이크 이상해!" 하고 취소 누름' },
        { emoji: '🔑', title: '차키/지갑 실종', desc: '바빠 죽겠는데 차키나 지갑 꼭 내가 방금 전까지 찾아본 곳 밑에서 발견됨.', actionLeft: '안도하며 허겁지겁 나감', actionRight: '나 자신의 멍청함에 분노하며 벽침' },
        { emoji: '🛒', title: '카트 고장', desc: '마트에서 카트 골랐는데 바퀴 하나 고장 나서 자꾸 오른쪽으로 쏠림.', actionLeft: '팔 근육 써서 억지로 끌고 다님', actionRight: '카트 발로 차고 장보기 포기' },
        { emoji: '🧊', title: '아아 참사', desc: '테이크아웃 아이스 아메리카노 컵홀더 헐거워져서 바닥에 뚝 떨어져 박살 남.', actionLeft: '눈물 흘리며 물티슈로 다 닦음', actionRight: '오열하며 바닥에 주저앉음' },
        { emoji: '🎧', title: '줄 꼬임', desc: '주머니에 1분 넣어둔 유선 이어폰 꺼냈는데 거미줄처럼 꼬여 있음.', actionLeft: '5분 걸려서 하나하나 풂', actionRight: '가위로 잘라버리고 에어팟 삼' },
        { emoji: '📺', title: '리모컨 꼭꼭 숨어라', desc: '채널 돌리려는데 리모컨 안 보여서 찾다 보니 내 엉덩이 밑에 깔려 있음.', actionLeft: '조용히 채널이나 바꿈', actionRight: '리모컨 바닥에 패대기침' },
        { emoji: '🚪', title: '손잡이 공격', desc: '바쁘게 걷다가 문손잡이나 가구 모서리에 바지 주머니 걸려서 뒤로 확 젖혀짐.', actionLeft: '찢어진 바지 보며 슬퍼함', actionRight: '문손잡이 부여잡고 쌍욕함' },
        { emoji: '🍞', title: '잼 바른 빵', desc: '식빵에 잼 발라서 들고 가다 놓쳤는데 정확히 잼 발린 쪽이 바닥으로 떨어짐.', actionLeft: '3초 룰 적용해서 주워 먹음', actionRight: '빵 밟아버리고 출근함' },
        { emoji: '👀', title: '시선 회피', desc: '길 걷다가 멀리서 아는 사람 발견해서 시선 피했는데, 상대방도 나 피해서 같은 방향으로 몸 틀음.', actionLeft: '어색하게 미소 지으며 인사함', actionRight: '뒤로 돌아 미친듯이 뛰어감' },
        { emoji: '💇‍♂️', title: '망한 미용실', desc: '미용실에서 머리 망쳤는데 거울 보고 "네 맘에 들어요^^" 하고 나와서 집에서 울음.', actionLeft: '모자 푹 눌러쓰고 다님', actionRight: '삭발하고 절에 들어감' },
        { emoji: '⏰', title: '5분만 더', desc: '아침에 "5분만 더 자야지" 하고 눈 감았다 떴는데 1시간 30분 지나있음.', actionLeft: '세수만 하고 빛의 속도로 나감', actionRight: '"어차피 늦은거" 하고 반차 냄' }
    ]
};
